name: Publish

on:
  release:
    types:
      - released

jobs:
  publish:
    name: MavenCentral Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Gradle
        run: gradle wrapper
      - name: Granted permissions
        run: chmod +x ./gradlew
      - name: Publish to MavenCentral
        run: ./gradlew lib:publishReleasePublicationToSonatypeRepository
        env:
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
          OSSRH_PROFILE_ID: ${{secrets.OSSRH_PROFILE_ID}}
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          SIGNING_KEY_ID: ${{secrets.SIGNING_KEY_ID}}
          SIGNING_KEY_X64: ${{secrets.SIGNING_KEY_X64}}
          SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
